INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (1, 'PORTUGUES', 'Leitura e interpretação de texto');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (2, 'PORTUGUES', 'Variação linguística');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (3, 'PORTUGUES', 'Gêneros textuais');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (4, 'PORTUGUES', 'Morfologia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (5, 'PORTUGUES', 'Sintaxe');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (6, 'PORTUGUES', 'Concordância');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (7, 'PORTUGUES', 'Regência');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (8, 'PORTUGUES', 'Crase');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (9, 'PORTUGUES', 'Pontuação');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (10, 'PORTUGUES', 'Ortografia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (11, 'PORTUGUES', 'Figuras de linguagem');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (12, 'MATEMATICA', 'Estatística');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (13, 'MATEMATICA', 'Aritmética');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (14, 'MATEMATICA', 'Geometria');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (15, 'MATEMATICA', 'Funções');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (16, 'MATEMATICA', 'Probabilidade');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (17, 'MATEMATICA', 'Trigonometria');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (18, 'HISTORIA', 'Antiguidade Clássica');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (19, 'HISTORIA', 'Feudalismo');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (20, 'HISTORIA', 'Absolutismo');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (21, 'HISTORIA', 'Revolução Francesa');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (22, 'HISTORIA', 'História do Brasil');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (23, 'FISICA', 'Mecânica');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (24, 'FISICA', 'Eletricidade');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (25, 'FISICA', 'Calorimetria');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (26, 'FISICA', 'Óptica');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (27, 'FISICA', 'Ondulatória');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (28, 'FISICA', 'Magnetismo');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (29, 'FISICA', 'Termofísica');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (30, 'FISICA', 'Leis de Newton');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (31, 'GEOGRAFIA', 'Cartografia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (32, 'GEOGRAFIA', 'Geomorfologia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (33, 'GEOGRAFIA', 'Solos');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (34, 'GEOGRAFIA', 'Climatologia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (35, 'GEOGRAFIA', 'Hidrografia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (36, 'GEOGRAFIA', 'Biogeografia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (37, 'GEOGRAFIA', 'Demografia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (38, 'GEOGRAFIA', 'Geopolítica ');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (39, 'QUIMICA', 'Eletroquímica');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (40, 'QUIMICA', 'Separação de misturas');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (41, 'QUIMICA', 'Cinética');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (42, 'QUIMICA', 'Reações orgânicas');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (43, 'QUIMICA', 'Tabela periódica');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (44, 'BIOLOGIA', 'Citologia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (45, 'BIOLOGIA', 'Genética');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (46, 'BIOLOGIA', 'Fisiologia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (47, 'BIOLOGIA', 'Biotecnologia');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (69, 'INGLES', 'Leitura e interpretação de texto');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (48, 'INGLES', 'Simple present');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (49, 'INGLES', 'Present continuous');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (50, 'INGLES', 'Past continuous');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (51, 'INGLES', 'Simple past');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (52, 'QUIMICA', 'Simple future');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (53, 'QUIMICA', 'Future continuous');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (54, 'INFORMATICA', 'Informática Básica');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (55, 'INFORMATICA', 'Arquitetura de Computadores');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (56, 'INFORMATICA', 'Redes de Computadores');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (57, 'INFORMATICA', 'Engenharia de Software');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (58, 'INFORMATICA', 'Banco de Dados');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (59, 'INFORMATICA', 'Programação');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (60, 'INFORMATICA', 'Inteligência Artificial');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (61, 'INFORMATICA', 'Segurança da Informação');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (62, 'INFORMATICA', 'Sistemas Operacionais');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (63, 'DIREITO', 'Direito Constitucional');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (64, 'DIREITO', 'Direito Administrativo');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (65, 'DIREITO', 'Direito Penal');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (66, 'DIREITO', 'Direito Civil');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (67, 'DIREITO', 'Direito Eleitoral');
INSERT INTO assunto (pk_assunto, disciplina , descricao) VALUES (68, 'DIREITO', 'Direito do Trabalho');
